server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/orderdb}
      repositories:
        enabled: true

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/orderdb?authSource=admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb_test
