name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  actions: read
  checks: write

env:
  JAVA_VERSION: '21'
  DOCKER_IMAGE: 'arkvemuri/order-service'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.version.outputs.version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version from tag
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven

    - name: Update version in pom.xml
      run: |
        mvn versions:set -DnewVersion=${{ steps.version.outputs.version }}
        mvn versions:commit

    - name: Build and test
      run: mvn clean verify

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }} .
        docker build -t ${{ env.DOCKER_IMAGE }}:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker images
      run: |
        docker push ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}
        docker push ${{ env.DOCKER_IMAGE }}:latest

    - name: Generate changelog
      id: changelog
      run: |
        # Generate changelog from git commits since last tag
        LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$LAST_TAG" ]; then
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
        else
          CHANGELOG=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s (%h)" --no-merges)
        fi
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.version.outputs.version }}
        body: |
          ## Changes in this Release
          ${{ steps.changelog.outputs.changelog }}
          
          ## Docker Images
          - `${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}`
          - `${{ env.DOCKER_IMAGE }}:latest`
          
          ## Installation
          ```bash
          docker pull ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version }}
          ```
        files: |
          target/order-${{ steps.version.outputs.version }}.jar
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

  update-gitops-release:
    name: Update GitOps for Release
    runs-on: ubuntu-latest
    needs: [release]
    
    steps:
    - name: Update GitOps for Production Release
      env:
        GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      run: |
        if [ -z "$GITOPS_TOKEN" ]; then
          echo "⚠️  GITOPS_TOKEN not configured. Skipping GitOps repository update."
          echo "To enable GitOps updates, set the GITOPS_TOKEN repository secret."
          exit 0
        fi
        
        # Checkout GitOps repository
        git clone https://$GITOPS_TOKEN@github.com/arkvemuri/deployment-folder.git
        cd deployment-folder
        
        # Update production manifest
        IMAGE_TAG="${{ env.DOCKER_IMAGE }}:${{ needs.release.outputs.version }}"
        sed -i "s|image:.*|image: ${IMAGE_TAG}|g" aws/order-manifest-prod.yml
        
        # Create a new release branch
        git checkout -b release-${{ needs.release.outputs.version }}
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        git add aws/order-manifest-prod.yml
        git commit -m "Release ${{ needs.release.outputs.version }}: Update order-service image"
        git push origin release-${{ needs.release.outputs.version }}

    - name: Create Pull Request for Production Deployment
      env:
        GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      run: |
        if [ -z "$GITOPS_TOKEN" ]; then
          echo "⚠️  GITOPS_TOKEN not configured. Skipping PR creation."
          exit 0
        fi
        
        # Create PR using GitHub CLI
        cd deployment-folder
        gh pr create \
          --title "Release ${{ needs.release.outputs.version }}: Deploy order-service to production" \
          --body "Automated release deployment for order-service version ${{ needs.release.outputs.version }}" \
          --head "release-${{ needs.release.outputs.version }}" \
          --base "main" \
          --repo "arkvemuri/deployment-folder"
        script: |
          const { data: pullRequest } = await github.rest.pulls.create({
            owner: 'arkvemuri',
            repo: 'deployment-folder',
            title: `Release ${{ needs.release.outputs.version }}: Deploy order-service to production`,
            head: 'release-${{ needs.release.outputs.version }}',
            base: 'main',
            body: `## Production Deployment Request
            
            This PR updates the production deployment manifest for order-service release ${{ needs.release.outputs.version }}.
            
            ### Changes:
            - Updated image tag to: \`${{ env.DOCKER_IMAGE }}:${{ needs.release.outputs.version }}\`
            
            ### Release Notes:
            See [Release ${{ needs.release.outputs.version }}](https://github.com/arkvemuri/order-service/releases/tag/v${{ needs.release.outputs.version }}) for details.
            
            **Please review and merge to deploy to production.**`
          });
          
          console.log(\`Created PR #\${pullRequest.number}\`);

  notify-release:
    name: Notify Release
    runs-on: ubuntu-latest
    needs: [release, update-gitops-release]
    if: always()
    
    steps:
    - name: Notify success
      if: needs.release.result == 'success'
      run: |
        echo "🎉 Release ${{ needs.release.outputs.version }} created successfully!"
        echo "Docker image: ${{ env.DOCKER_IMAGE }}:${{ needs.release.outputs.version }}"
        # Add your notification logic here (Slack, Teams, etc.)

    - name: Notify failure
      if: failure()
      run: |
        echo "❌ Release process failed!"
        # Add failure notification logic here